### ISSUE TITLE
Create shows.yml from FB events

### ISSUE THREAD

**Issue by charles-hood** [TheRobBrennan/woatw#42]
Have you considered importing Facebook events and using them to create the shows.yml file automatically?
This is something I've been able to do with a python script, let me know if you're interested.
I used this project: https://github.com/berettavexee/events-scrapper
(It was designed to create an ical, but I hacked it to create shows.yml)

**Comment by TheRobBrennan** [comment]
Hi @charles-hood! Hm that is an idea - particularly since I know the show dates are currently long in the tooth LOL

Been taking more of a look at Next.js and Hasura recently. The Gatsby stuff has been fun to work with, but the engineering bug in me is bit hard and eager to chase that some...among the thousand other items I have on my plate haha

Hope you had a great holiday weekend ::fist bump::
